### ISSUE TITLE
16-bit PNG input

### ISSUE THREAD

**Issue by p0nce** [lgvz/imageformats#17]
I use imageformats for loading depth maps made with GIMP, the problem is that 8-bit aren't sufficient to represent depth without the normals going crazy.

**Comment by ghost** [comment]
I'll have to take look how to do this

**Comment by p0nce** [comment]
Would you take Bountysource for this?
What would be your price?

**Comment by ghost** [comment]
No need, I have it working, just need to clean it up.

**Comment by p0nce** [comment]
Great news!

**Comment by ghost** [comment]
Hold your breath!

**Comment by ghost** [comment]
Check out the `png-16-bit` branch. Everything works, except 16-bit interlaced gray+alpha images don't decode properly (e.g. `basi4a16.png` & `bgai4a16.png` in png suite). It looks like it's related to interlacing. Some length or indexing must be wrong somewhere...

**Comment by p0nce** [comment]
I'll check it in the following week. At the moment I just need RGB without alpha.

**Comment by ghost** [comment]
It's fixed and in master now. Any comments before I make a release?

**Comment by p0nce** [comment]
A big thank you.
Currently I load an 8 bit depth map and add a bit of noise, this has forced me to make interfaces more flat that I would like (https://github.com/p0nce/dplug/raw/master/screenshot.jpg <= this uses imageformats to load background images). Any difference of 1 in the background in an oblique way would render normals crazy. This will allow me to create more round shapes and avoid putting noise everywhere.
