### ISSUE TITLE
 cannot implicitly convert expression (dc.w * 3L) of type long t o uint

### ISSUE THREAD

**Issue by bubnenkoff** [lgvz/imageformats#2]
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(316): Error: cannot implicitly convert expression (dc.w \* 3L) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(317): Error: cannot implicitly convert expression (dc.w \* dc.h \* cast(long)d
c.tgt_chans) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(323): Error: cannot implicitly convert expression (s) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(326): Error: cannot implicitly convert expression (d) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(326): Error: cannot implicitly convert expression (d + 3L) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(339): Error: cannot implicitly convert expression (src_sl_size + 1L) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(340): Error: cannot implicitly convert expression (src_sl_size + 1L) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(349): Error: cannot implicitly convert expression (tgt_si) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(349): Error: cannot implicitly convert expression (tgt_si + tgt_linesize) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(379): Error: cannot implicitly convert expression (max_scanline_size + 1L) o
f type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(380): Error: cannot implicitly convert expression (max_scanline_size + 1L) o
f type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(381): Error: cannot implicitly convert expression (dc.w \* cast(long)dc.tgt_c
hans) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(386): Error: cannot implicitly convert expression (src_linesize + 1L) of typ
e long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(387): Error: cannot implicitly convert expression (src_linesize + 1L) of typ
e long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(394): Error: cannot implicitly convert expression (redw[cast(uint)pass] \* ca
st(long)dc.tgt_chans) of type long to uint
C:\Users\bubenkov_di\AppData\Roaming\dub\packages\imageformats-3.0.4\imageformat
s.d(398): Error: cannot implicitly convert expression (tgt) of type long to uint

I can't understand why I am getting this error.

**Comment by ghost** [comment]
Fixed.
