### ISSUE TITLE
Tests fail on travis with LDC 

### ISSUE THREAD

**Issue by p0nce** [lgvz/imageformats#22]
I'm not sure why the test here failed: https://travis-ci.org/d-gamedev-team/gfm/jobs/104226000#L275
Could be Travis hasard.

**Comment by ghost** [comment]
This:

```
stdio.d(472): Cannot open file `tests/pngsuite/basi0g08.png' in mode `rb' (No such file or directory)
```

is not a problem with imageformats. The file is in the repo and readable. The problem must be somewhere else... and ldc works fine on my machine so I guess it's Travis. I'll close this.
