### ISSUE TITLE
Excess memory usage.

### ISSUE THREAD

**Issue by p0nce** [lgvz/imageformats#26]
Loading a 763 x 494 PNG makes about 9mb of garbage (when the decompressed images fits on 1.5 mb).
Tested on Windows 32-bit. I think I've traced it back the to Zlib decompression in PNG loading.
For each PNG line, the zlib call to `uncompress` makes a new to create a new buffer to return.
What could we do, perhaps have a @nogc Zlib equivalent?

**Comment by rjmcguire** [comment]
Does UnCompress.uncompress break something that there is a .dup here? surely its safe not to dup?

https://github.com/lgvz/imageformats/blob/master/imageformats/png.d#L545

```
        dc.uc_buf = cast(ubyte[]) dc.uc.uncompress(dc.read_buf[0..bytes].dup);
```

**Comment by p0nce** [comment]
@rjmcguire could help, I'll try.

This problem isn't only in imageformats:
https://forum.dlang.org/post/spyxbdamfdchzebnkgeo@forum.dlang.org

Other people have found that std.zlib makes lots of allocations that the GC doesn't collect well.

**Comment by rjmcguire** [comment]
hmm, maybe the .dup is there for a reason:

> adamdruppe
> 
> > Well, It works on LDC x64! again ;) This seems like an issue with DMD x64? I was thinking maybe it has to do the layout of the struct or something, but not sure.
> 
> I have a fix for this too, though I don't understand why it works....
> 
> I just .dup'd the string literal before passing it to Windows. I think dmd is putting the literal in a bad place for these functions (they do bit tests to see if it is a pointer or an atom, so maybe it is in an address where the wrong bits are set)

**Comment by p0nce** [comment]
Yeah, it crashes without that .dup

**Comment by ghost** [comment]
So fixing `std.zlib` seems like the way to go. You could make `imageformats` use `etc.zlib` directly but that's the job of `std.zlib`, really.

**Comment by p0nce** [comment]
I tried and failed to do so.

**Comment by ghost** [comment]
There's a @nogc remake that should not have this issue at all (it uses `etc.c.zlib`): https://github.com/lgvz/imagefmt. It avoids memcopies as well except for reading 12 bytes of metadata per chunk and whatever copies occasionally calling the io read function does. The imageformats code is really dumb, the png encoder of it also sucks, it's such a lazy piece of work. (edit: updated link)

**Comment by p0nce** [comment]
Oh my! We really need someone like you in DlangGraphicsWG! 
https://github.com/DlangGraphicsWG

Current work that has been done is: colors, images (with meta-data), and BMP and PNG parser (which also fix the zlib problem). If you'd like to collaborate on this, it's a workgroup with people that all have made libraries related to "UI" and would like a good one in D.

**Comment by ghost** [comment]
I'll decline since I have lots of other plans for my time. Thanks for the invite, though.

**Comment by ghost** [comment]
I finally adapted code from imagefmt to fix this.
