### ISSUE TITLE
BMP Support

### ISSUE THREAD

**Issue by WebFreak001** [lgvz/imageformats#3]
I'd like to have bmp support. Its also super simple because its mainly just magic value -> uncompressed bytes

**Comment by ghost** [comment]
I might add it when I have time. Apparently doesn't require much code.

**Comment by ghost** [comment]
~~Actually I'm not going to put my time into this but if someone else implements it, I'll merge it.~~ I take that back. @WebFreak001 it's not quite just magic value + bytes. The headers, when properly parsed, seem to be somewhat of a mess. But I already have a Rust version, so I might as well port it to D, too.
