### ISSUE TITLE
Support CMYK color model in JPEG

### ISSUE THREAD

**Issue by carun** [lgvz/imageformats#33]
JPEG decoder doesn't support CMYK color model. Sample image from https://upload.wikimedia.org/wikipedia/en/2/25/Channel_digital_image_CMYK_color.jpg

![Sample image](https://upload.wikimedia.org/wikipedia/en/2/25/Channel_digital_image_CMYK_color.jpg)

**Comment by ghost** [comment]
Yeah. I mean to keep this package simple and not support everything. I'm also on a only-fix-bugs-maintenance mode with this anyway.

**Comment by carun** [comment]
I see. DCV uses imageformats package and most of the times the input to DCV can be any format. Sad that there is no comprehensive image decoder (like opencv) in D.
