### ISSUE TITLE
some PNG images break pixel order.

### ISSUE THREAD

**Issue by SuperDoxin** [lgvz/imageformats#7]
I've been trying to roundtrip some png images using the following code:

```
import std.stdio;
import imageformats;
import std.conv;
import core.memory;

struct Image
    {
    float[3][][] pixels;
    size_t width;
    size_t height;
    void from_file(string filename)
        {
        IFImage im=read_image(filename);
        this.width=im.w;
        this.height=im.h;
        this.pixels=new float[3][][](this.width,this.height);
        size_t i=0;

        for(size_t x;x<this.height;x+=1)
        for(size_t y;y<this.width;y+=1)
        for(size_t c;c<3;c+=1)
            {
            this.pixels[x][y][c]=(im.pixels[i].to!float)/128-1;
            i+=1;
            }
        }
    void save(string filename)
        {
        auto npixels=new ubyte[this.width*this.height*3];
        size_t i=0;
        for(size_t x;x<this.height;x+=1)
        for(size_t y;y<this.width;y+=1)  
        for(size_t c;c<3;c+=1)
            {
            npixels[i]=((this.pixels[x][y][c]+1)*128).to!ubyte;
            i+=1;
            }
        if(filename[$-4 .. $]==".png")
            write_png(filename,this.width,this.height,npixels);
        else if(filename[$-4 .. $]==".tga")
            write_tga(filename,this.width,this.height,npixels);
        else
            throw new Exception("unknown file extension");
        }
    }


void main()
    {
    Image img;
    img.from_file("test_in.png");
    img.save("test.png");
    }
```

but for some png images this outputs a mangled image. even including such a broken png in another image using the gimp breaks the output.

![tests_compiled](https://cloud.githubusercontent.com/assets/377239/8962870/4e0687e4-361d-11e5-8e75-a26376c14c99.png)
1. image working correctly.
2. broken image pasted onto working image using the Gimp.
3. broken image pasted onto working image with 0% opacity using the Gimp.

evidently there is some format of PNG that this library implements incorrectly.

I've included the files used in this testcase in [this zip file](https://app.box.com/s/e6nluzupk1m9jarafsylskpzhwvawhfr). test_n_.png as output, and test_n__in.png as input.

**Comment by ghost** [comment]
The problem is that your image is RGBA data, but your code treats it as RGB. To convert it to RGB as you load the image, change the line
`IFImage im=read_image(filename);`
to
`IFImage im=read_image(filename, ColFmt.RGB);`
