### ISSUE TITLE
do not depend on file extension

### ISSUE THREAD

**Issue by sigod** [lgvz/imageformats#8]
It would be very useful to have functions like `read_image` and `read_image_info`, that wouldn't depend on file extension.

Same for `write_image`.

For example, `vibe-d` uses temporary names for uploaded files:

``` d
writeln(req.files["file"].tempPath.toString); // /tmp/vtmp.oBoYOM
```

As you see it leads to a certain problems.

**Comment by ghost** [comment]
I see. For writing, you could use the format specific functions.

**Comment by ghost** [comment]
Well I added detection.

**Comment by sigod** [comment]
Thanks. I'll try it in a few days.
